Repository openshift/node-problem-detector-operator, pull requests merged in 2018-10, with the labels that each got.

#3 Hard-code NPD to openshift-node-problem-detector NS
  README.md
  deploy/cr.yaml
  deploy/operator.yaml
  deploy/rbac.yaml
  deploy/sa.yaml
  pkg/stub/handler.go
Labels: size/M

#4 Fix CR param ImagePullPolicy and remove vestigial CR params
  pkg/apis/node-problem-detector/v1alpha1/types.go
  pkg/stub/handler.go
Labels: size/XS

#7 Add OLM catalog data
  deploy/olm-catalog/crd.yaml
  deploy/olm-catalog/csv.yaml
  deploy/olm-catalog/package.yaml
Labels: lgtm, size/M

#6 change image path to CI built image
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#8 add kubelet problem plugin support
  pkg/stub/handler.go
Labels: approved, lgtm, size/M
